routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/* Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home'); */

Route::get('/', function(){
    return redirect('/blogs');
});

Route::resource('blogs', 'BlogController');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = [
        'title',
        'description',
        'name',
     ];

     protected $dates = [
         'updated_at',
     ];//eloquent for converting to carbon
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::all(); //Getting Data from the Blog Model
        return view('blogs.index', ['allBlogs' => $blogs]); //Passing Blog Post Data to index view
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Blog::create([
            'title' => $request->input('title'),
            'name' => $request->input('name'),
            'description' => $request->input('post'),
        ]);//eloquent insert record from view

        return redirect('/blogs')->with('success', 'Blog Post Created.'); //redirect with success message
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        return view('blogs.show', compact('blog'));//showing each individual blog post
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        return view('blogs.edit', compact('blog'));//
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        $blog->update($request->all());//getting updated values from view and updating record

        return redirect()->route('blogs.index')->with('success', 'Blog Post Updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $blog->delete();

        return redirect()->route('blogs.index')->with('success', 'Blog Post Deleted.'); //deleting blog post with success message
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/blogs/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <title>Blog</title>

</head>


<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        
        <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
            <div class="d-flex flex-grow-1">
                <span class="w-100 d-lg-none d-block">
                    <!-- hidden spacer to center brand on mobile --></span>
                <a class="navbar-brand d-none d-lg-inline-block ms-4" href="#"> My Blog </a>
                <a class="navbar-brand-two mx-auto d-lg-none d-inline-block" href="#"></a>
                <div class="w-100 text-right">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>
            <ul class="navbar-nav ms-auto flex-nowrap me-4">
                <li class="nav-item me-2">
                    <a href="/blogs" class="nav-link menu-item nav-active">Home</a>
                </li>
                <li class="nav-item">
                    <a href="/blogs/create" class="nav-link menu-item">Create Blog Post</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <main class="py-4">
        @yield('content')
    </main>


<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="{{ asset('js/app.js') }}" defer></script>

</body>
</html>

resources/views/blogs/create.blade.php
@extends('blogs.app')

@section('content')

<div class="container">
    <div class="justify-content-center">
        <form method="POST" action="{{ route('blogs.store')}}">
            @csrf
            <h1> New Blog Post</h1>
            <div class="row mt-4">
                <div class="col-6">
                <label for="WriterName">Writer Name</label>
                <input type="text" class="form-control" id="WriterName" name="name" required>
                </div>

                <div class="col-6">
                <label for="title">Post Title</label>
                <input type="text" class="form-control" name="title" required>
                </div>
            
            </div>

                <div class="mt-4">
                    <div class="form-group col-md-12 mt-2">
                        <label for="post">Blog Post</label>
                        <textarea class="form-control" name="post" rows="10" required></textarea>
                    </div>
                </div>

            <button type="submit" class="btn btn-info mt-4 col-4">Submit</button>
            
        </form>
    </div>
</div>


@endsection

resources/views/blogs/edit.blade.php
@extends('blogs.app')

@section('content')

<div class="container">
    <div class="justify-content-center">
        <form method="POST" action="{{ route('blogs.update', $blog->id) }}">
            @csrf
            @method('PUT')
            <h1> New Blog Post</h1>
            <div class="row mt-4">
                <div class="col-6">
                <label for="WriterName">Writer Name</label>
                <input type="text" class="form-control" id="WriterName" name="name" value="{{ $blog->name}}" required>
                </div>

                <div class="col-6">
                <label for="title">Post Title</label>
                <input type="text" class="form-control" name="title" value="{{ $blog->title }}" required>
                </div>
            
            </div>

                <div class="mt-4">
                    <div class="form-group col-md-12 mt-2">
                        <label for="post">Blog Post</label>
                        <textarea class="form-control" name="post" rows="10" required>{{ $blog->description }}</textarea>
                    </div>
                </div>

            <button type="submit" class="btn btn-info mt-4 col-4">Update</button>
            
        </form>
    </div>
</div>


@endsection

resources/views/blogs/index.blade.php
@extends('blogs.app')

@section('content')

<div class="container">
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show ">
            <p>{{ $message }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    {{-- a foreach loop is run through to get all the blog posts found and accessing the title,name, post and last updated time --}}
    @foreach ($allBlogs as $blog)
    <div class="row mt-4">

        <article>
            <h2 class="display-5">{{ $blog->title }}</h2>
            
            <span class="text-muted"><a>Written By: {{ $blog->name}} , Last Updated at {{$blog->updated_at->format('H:i:s A')}}</a></span>
            

            <div class="row mt-4">
                <p>{{ Str::limit($blog->description, 500, ' ...') }}</p>
            </div>

            <form action="{{ route('blogs.show', $blog->id) }}" method="GET">
                @csrf
            <button class="btn btn-primary">Read More</button>
            </form> {{-- the button is routed to show the specific blog post in detail --}}

        </article>
        
    </div>
    @endforeach

</div>


@endsection

resources/views/blogs/show.blade.php
@extends('blogs.app')

@section('content')

<div class="container">
    <div class="row mt-4">

        <article>
            <h2 class="display-5">{{ $blog->title }}</h2>
            
            <span class="text-muted"><a>Written By: {{ $blog->name}} , Last Updated at {{$blog->updated_at->format('H:i:s A')}}</a></span>
            

            <div class="row mt-4">
                <p>{{ $blog->description }}</p>
            </div>

            <form action="{{ route('blogs.destroy', $blog->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <a class="btn btn-warning" role="button" href="{{ route('blogs.edit', $blog->id) }}" > Edit Blog Post</a>
                <button type="submit" class="btn btn-danger ms-4">Delete Blog Post</button>
            </form>

        </article>
        
    </div>

</div>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>